"""Audit added

Revision ID: 3918d62f77f1
Revises: 6dc5137189b6
Create Date: 2026-10-08 13:22:52.687356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3918d62f77f1'
down_revision: Union[str, Sequence[str], None] = '6dc5137189b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'FUNCIONARIO', name='userrole'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column('categories', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('categories', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('categories', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'categories', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'categories', 'users', ['deleted_by'], ['id'])
    op.add_column('products', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['deleted_by'], ['id'])
    op.drop_column('products', 'data_created')
    op.add_column('stock_movements', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('stock_movements', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'stock_movements', 'users', ['created_by'], ['id'])
    op.drop_column('stock_movements', 'data_created')
    op.add_column('suppliers', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('suppliers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('suppliers', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('suppliers', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'suppliers', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'suppliers', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'suppliers', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'deleted_at')
    op.drop_column('suppliers', 'deleted_by')
    op.drop_column('suppliers', 'updated_at')
    op.drop_column('suppliers', 'updated_by')
    op.drop_column('suppliers', 'created_at')
    op.drop_column('suppliers', 'created_by')
    op.add_column('stock_movements', sa.Column('data_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_column('stock_movements', 'created_at')
    op.drop_column('stock_movements', 'created_by')
    op.add_column('products', sa.Column('data_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'products', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'products', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'deleted_by')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'updated_by')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'created_by')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'categories', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'categories', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'deleted_at')
    op.drop_column('categories', 'deleted_by')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'updated_by')
    op.drop_column('categories', 'created_at')
    op.drop_column('categories', 'created_by')
    op.drop_table('users')
    # ### end Alembic commands ###
